version: '3'
services:
  php:
    container_name: shop-php
    build:
      context: ./docker-conf/php
    image: shop-php
    volumes:
      - ./:/app
    networks:
      - shop-networks
  nginx:
    container_name: shop-nginx
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker-conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - shop-networks
networks:
  shop-networks:
    name: shop-networks
    
